spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: springboot
    url: jdbc:mysql://localhost:3306/springboot
    username: springboot

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  info:
    app:
      description: This is auth service on spring boot application
      name: Auth Service
      version: 1.0.0
