server:
  port: 8761
spring:
  application:
    name: eureka-server


  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      password: springboot
      url: jdbc:mysql://localhost:3306/springboot
      username: springboot


eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
